### PR TITLE
use mocha for testing

### PR DESCRIPTION
**Pull request by BFergerson**
- Tests with mocha instead of gradle/kotlin
- Added probe config `spp-probe.host`, `spp-probe.grpc_port`, `spp-probe.rest_host`
   - will change other probes to use this config via https://github.com/sourceplusplus/live-platform/issues/452

### CODE REVIEW

**Comment by BFergerson** [comment]
@MrMineO5, do you know how to fix `SyntaxError: Cannot use import statement outside a module`? I'm trying to get this to work: https://github.com/sourceplusplus/probe-nodejs/blob/bfdc62eaf4035372b408c9ff10174219e56d9f33/test/test.js#L108

**Comment by MrMineO5** [comment]
You can't require the typescript files in a javascript file, a functional, but suboptimal solution is to use ../dist/SourcePlusPlus.js

**Comment by BFergerson** [comment]
Thanks, that worked. Can you please review? I'm new to testing with mocha but I think this style of testing is more suitable for this project. There's a lot of baggage in include Kotlin/Gradle.

**Comment by BFergerson** [comment]
The test JWT tokens don't have an expiration date, but yes, ideally they should be generating the JWT token.

**Review by MrMineO5 — APPROVED** [review]

**Pull request merged**
