### PR TITLE
test: simple primitives

### PR DESCRIPTION
**Pull request by BFergerson**

### CODE REVIEW

**Comment by BFergerson** [comment]
@MrMineO5, modeled the new tests after the design of [SimplePrimitivesLiveInstrumentTest](https://github.com/sourceplusplus/live-platform/blob/9782fde8471a1c3f2e2a80909bde5f82b67f36f1/platform/processor/live-instrument/src/test/kotlin/integration/SimplePrimitivesLiveInstrumentTest.kt#L35).

I had some trouble implementing it with OOP so ended up using a utility class.
Any thoughts on how to improve the design?

**Comment by MrMineO5** [comment]
Why are you returning a function that returns the file name in TestUtils.getFilename?

**Comment by BFergerson** [comment]
Something I copied from the JVM implementation. I wanted the source and line numbers of the live instruments to be dynamic so you can move the files around and modify them without breaking them. Adding `TestUtils.getFilename` should allow you to rename that file and the test will still pass.

**Comment by BFergerson** [comment]
@MrMineO5, thanks for the improvments. I like how these tests are coming out. Looks very easy to maintain.

**Pull request merged**
